apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  selector:
    app: traefik
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: admin
    port: 8080
    protocol: TCP
    targetPort: admin
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: ping
    port: 5555
    protocol: TCP
    targetPort: ping
  type: NodePort
